# Generated by Django 4.0 on 2022-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_signup',
            fields=[
                ('custid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('socialmedia', models.CharField(max_length=155)),
                ('formal_education', models.CharField(max_length=50)),
                ('smoking', models.CharField(max_length=10)),
                ('securityquestion', models.CharField(max_length=155)),
                ('questionanswer', models.CharField(max_length=155)),
            ],
        ),
    ]
