# Generated by Django 4.0 on 2022-05-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0002_cust_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cust_signup',
            new_name='CustSignup',
        ),
    ]
