# Generated by Django 4.0 on 2022-05-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0003_rename_cust_signup_custsignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custsignup',
            name='questionanswer',
        ),
        migrations.RemoveField(
            model_name='custsignup',
            name='securityquestion',
        ),
        migrations.RemoveField(
            model_name='custsignup',
            name='smoking',
        ),
    ]
