# Generated by Django 4.0 on 2022-07-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0004_remove_custsignup_questionanswer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustSignup',
            new_name='CustEnquiry',
        ),
    ]
