# Generated by Django 4.0 on 2022-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0005_rename_custsignup_custenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odb',
            name='custid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
