# Generated by Django 4.0 on 2022-07-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0006_alter_odb_custid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='odb',
        ),
    ]
