# Generated by Django 4.0 on 2022-07-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudding', '0008_odb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odb',
        ),
    ]
